import { TetrominoType, WordBook } from './types';

export const BOARD_WIDTH = 12; // Divisible by 4 for zones
export const BOARD_HEIGHT = 20;

export const TETROMINOS: Record<TetrominoType, number[][][]> = {
  [TetrominoType.I]: [
    [[0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0]],
    [[0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0]],
    [[0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0]],
    [[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0]],
  ],
  [TetrominoType.J]: [
    [[1, 0, 0], [1, 1, 1], [0, 0, 0]],
    [[0, 1, 1], [0, 1, 0], [0, 1, 0]],
    [[0, 0, 0], [1, 1, 1], [0, 0, 1]],
    [[0, 1, 0], [0, 1, 0], [1, 1, 0]],
  ],
  [TetrominoType.L]: [
    [[0, 0, 1], [1, 1, 1], [0, 0, 0]],
    [[0, 1, 0], [0, 1, 0], [0, 1, 1]],
    [[0, 0, 0], [1, 1, 1], [1, 0, 0]],
    [[1, 1, 0], [0, 1, 0], [0, 1, 0]],
  ],
  [TetrominoType.O]: [
    [[1, 1], [1, 1]],
    [[1, 1], [1, 1]],
    [[1, 1], [1, 1]],
    [[1, 1], [1, 1]],
  ],
  [TetrominoType.S]: [
    [[0, 1, 1], [1, 1, 0], [0, 0, 0]],
    [[0, 1, 0], [0, 1, 1], [0, 0, 1]],
    [[0, 0, 0], [0, 1, 1], [1, 1, 0]],
    [[1, 0, 0], [1, 1, 0], [0, 1, 0]],
  ],
  [TetrominoType.T]: [
    [[0, 1, 0], [1, 1, 1], [0, 0, 0]],
    [[0, 1, 0], [0, 1, 1], [0, 1, 0]],
    [[0, 0, 0], [1, 1, 1], [0, 1, 0]],
    [[0, 1, 0], [1, 1, 0], [0, 1, 0]],
  ],
  [TetrominoType.Z]: [
    [[1, 1, 0], [0, 1, 1], [0, 0, 0]],
    [[0, 0, 1], [0, 1, 1], [0, 1, 0]],
    [[0, 0, 0], [1, 1, 0], [0, 1, 1]],
    [[0, 1, 0], [1, 1, 0], [1, 0, 0]],
  ],
};

export const COLORS: Record<TetrominoType, string> = {
  [TetrominoType.I]: '#00f0f0', // Cyan
  [TetrominoType.J]: '#0000f0', // Blue
  [TetrominoType.L]: '#f0a000', // Orange
  [TetrominoType.O]: '#f0f000', // Yellow
  [TetrominoType.S]: '#00f000', // Green
  [TetrominoType.T]: '#a000f0', // Purple
  [TetrominoType.Z]: '#f00000', // Red
};

export const WORD_BOOKS: WordBook[] = [
  {
    id: 'primary',
    name: '小学英语 (Primary)',
    words: [
      { english: 'Apple', chinese: '苹果' }, { english: 'Banana', chinese: '香蕉' }, { english: 'Cat', chinese: '猫' },
      { english: 'Dog', chinese: '狗' }, { english: 'Elephant', chinese: '大象' }, { english: 'Fish', chinese: '鱼' },
      { english: 'Girl', chinese: '女孩' }, { english: 'House', chinese: '房子' }, { english: 'Ice', chinese: '冰' },
      { english: 'Jump', chinese: '跳' }, { english: 'Kite', chinese: '风筝' }, { english: 'Lion', chinese: '狮子' },
      { english: 'Monkey', chinese: '猴子' }, { english: 'Nurse', chinese: '护士' }, { english: 'Orange', chinese: '橙子' },
      { english: 'Panda', chinese: '熊猫' }, { english: 'Queen', chinese: '女王' }, { english: 'Rabbit', chinese: '兔子' },
      { english: 'Snake', chinese: '蛇' }, { english: 'Tiger', chinese: '老虎' }, { english: 'Umbrella', chinese: '雨伞' },
      { english: 'Violin', chinese: '小提琴' }, { english: 'Water', chinese: '水' }, { english: 'X-ray', chinese: 'X光' },
      { english: 'Yellow', chinese: '黄色' }, { english: 'Zebra', chinese: '斑马' }, { english: 'Bird', chinese: '鸟' },
      { english: 'Duck', chinese: '鸭子' }, { english: 'Egg', chinese: '鸡蛋' }, { english: 'Flower', chinese: '花' },
      { english: 'Grass', chinese: '草' }, { english: 'Head', chinese: '头' }, { english: 'Island', chinese: '岛' },
      { english: 'Jelly', chinese: '果冻' }, { english: 'Key', chinese: '钥匙' }, { english: 'Lamp', chinese: '灯' },
      { english: 'Moon', chinese: '月亮' }, { english: 'Nose', chinese: '鼻子' }, { english: 'Owl', chinese: '猫头鹰' },
      { english: 'Pen', chinese: '钢笔' }, { english: 'Question', chinese: '问题' }, { english: 'Rain', chinese: '雨' },
      { english: 'Sun', chinese: '太阳' }, { english: 'Tree', chinese: '树' }, { english: 'Uncle', chinese: '叔叔' },
      { english: 'Van', chinese: '货车' }, { english: 'Watch', chinese: '手表' }, { english: 'Box', chinese: '盒子' },
      { english: 'Yo-yo', chinese: '溜溜球' }, { english: 'Zoo', chinese: '动物园' }, { english: 'Ant', chinese: '蚂蚁' },
      { english: 'Bear', chinese: '熊' }, { english: 'Cake', chinese: '蛋糕' }, { english: 'Desk', chinese: '书桌' },
      { english: 'Eye', chinese: '眼睛' }, { english: 'Foot', chinese: '脚' }, { english: 'Goat', chinese: '山羊' },
      { english: 'Hat', chinese: '帽子' }, { english: 'Ink', chinese: '墨水' }, { english: 'Jet', chinese: '喷气式飞机' },
      { english: 'King', chinese: '国王' }, { english: 'Leg', chinese: '腿' }, { english: 'Milk', chinese: '牛奶' },
      { english: 'Net', chinese: '网' }, { english: 'Ox', chinese: '公牛' }, { english: 'Pig', chinese: '猪' },
      { english: 'Rose', chinese: '玫瑰' }, { english: 'Star', chinese: '星星' }, { english: 'Tea', chinese: '茶' },
      { english: 'Under', chinese: '在...下面' }, { english: 'Vest', chinese: '背心' }, { english: 'Wall', chinese: '墙' },
      { english: 'Fox', chinese: '狐狸' }, { english: 'Yard', chinese: '院子' }, { english: 'Zero', chinese: '零' },
      { english: 'Book', chinese: '书' }, { english: 'Car', chinese: '汽车' }, { english: 'Door', chinese: '门' },
      { english: 'Ear', chinese: '耳朵' }, { english: 'Face', chinese: '脸' }, { english: 'Game', chinese: '游戏' },
      { english: 'Hand', chinese: '手' }, { english: 'Idea', chinese: '主意' }, { english: 'Job', chinese: '工作' },
      { english: 'Kid', chinese: '小孩' }, { english: 'Love', chinese: '爱' }, { english: 'Map', chinese: '地图' },
      { english: 'Name', chinese: '名字' }, { english: 'Old', chinese: '老的' }, { english: 'Park', chinese: '公园' },
      { english: 'Quiz', chinese: '测验' }, { english: 'Red', chinese: '红色' }, { english: 'School', chinese: '学校' },
      { english: 'Time', chinese: '时间' }, { english: 'Use', chinese: '使用' }, { english: 'Voice', chinese: '声音' },
      { english: 'Wind', chinese: '风' }, { english: 'Year', chinese: '年' }, { english: 'Zone', chinese: '区域' },
      { english: 'Art', chinese: '艺术' }, { english: 'Bus', chinese: '公共汽车' }, { english: 'Cow', chinese: '母牛' },
      { english: 'Day', chinese: '天' }, { english: 'Eat', chinese: '吃' }, { english: 'Fly', chinese: '飞' },
      { english: 'Gold', chinese: '金子' }, { english: 'Hair', chinese: '头发' }, { english: 'Ice cream', chinese: '冰淇淋' },
      { english: 'Juice', chinese: '果汁' }, { english: 'Knee', chinese: '膝盖' }, { english: 'Lake', chinese: '湖' },
      { english: 'Mouth', chinese: '嘴' }, { english: 'Neck', chinese: '脖子' }, { english: 'Open', chinese: '打开' },
      { english: 'Pear', chinese: '梨' }, { english: 'Quiet', chinese: '安静的' }, { english: 'Road', chinese: '路' },
      { english: 'Ship', chinese: '船' }, { english: 'Train', chinese: '火车' }, { english: 'Up', chinese: '向上' },
      { english: 'Vegetable', chinese: '蔬菜' }, { english: 'Walk', chinese: '走路' }, { english: 'Xylophone', chinese: '木琴' },
      { english: 'Yogurt', chinese: '酸奶' }, { english: 'Zip', chinese: '拉链' }, { english: 'Arm', chinese: '手臂' },
      { english: 'Bed', chinese: '床' }, { english: 'Chair', chinese: '椅子' }, { english: 'Doll', chinese: '洋娃娃' },
      { english: 'Eight', chinese: '八' }, { english: 'Five', chinese: '五' }, { english: 'Green', chinese: '绿色' },
      { english: 'Home', chinese: '家' }, { english: 'Insect', chinese: '昆虫' }, { english: 'Jacket', chinese: '夹克' },
      { english: 'Kitchen', chinese: '厨房' }, { english: 'Leaf', chinese: '叶子' }, { english: 'Mouse', chinese: '老鼠' },
      { english: 'Night', chinese: '夜晚' }, { english: 'One', chinese: '一' }, { english: 'Plane', chinese: '飞机' },
      { english: 'Quick', chinese: '快的' }, { english: 'Rice', chinese: '米饭' }, { english: 'Shoe', chinese: '鞋' },
      { english: 'Table', chinese: '桌子' }, { english: 'Uniform', chinese: '制服' }, { english: 'Village', chinese: '村庄' },
      { english: 'Window', chinese: '窗户' }, { english: 'Six', chinese: '六' }, { english: 'Yes', chinese: '是' },
      { english: 'Baby', chinese: '婴儿' }, { english: 'Ball', chinese: '球' }, { english: 'Coat', chinese: '外套' },
      { english: 'Dress', chinese: '连衣裙' }, { english: 'Farm', chinese: '农场' }, { english: 'Gate', chinese: '大门' },
      { english: 'Hill', chinese: '小山' }, { english: 'Ill', chinese: '生病的' }, { english: 'Jeep', chinese: '吉普车' },
      { english: 'Knife', chinese: '刀' }, { english: 'Lemon', chinese: '柠檬' }, { english: 'Meat', chinese: '肉' },
      { english: 'Nine', chinese: '九' }, { english: 'Oil', chinese: '油' }, { english: 'Photo', chinese: '照片' },
      { english: 'Room', chinese: '房间' }, { english: 'Sheep', chinese: '绵羊' }, { english: 'Teacher', chinese: '老师' },
      { english: 'University', chinese: '大学' }, { english: 'Visit', chinese: '参观' }, { english: 'Wolf', chinese: '狼' },
      { english: 'Box', chinese: '箱子' }, { english: 'Year', chinese: '年' }, { english: 'Zoo', chinese: '动物园' },
      { english: 'Sister', chinese: '姐妹' }, { english: 'Brother', chinese: '兄弟' }, { english: 'Father', chinese: '父亲' },
      { english: 'Mother', chinese: '母亲' }, { english: 'Grandpa', chinese: '爷爷' }, { english: 'Grandma', chinese: '奶奶' },
      { english: 'Friend', chinese: '朋友' }, { english: 'Class', chinese: '班级' }, { english: 'Desk', chinese: '课桌' },
      { english: 'Ruler', chinese: '尺子' }, { english: 'Pencil', chinese: '铅笔' }, { english: 'Bag', chinese: '书包' }
    ]
  },
  {
    id: 'middle',
    name: '初中英语 (Junior)',
    words: [
      { english: 'Ability', chinese: '能力' }, { english: 'Background', chinese: '背景' }, { english: 'Capital', chinese: '首都' },
      { english: 'Dangerous', chinese: '危险' }, { english: 'Education', chinese: '教育' }, { english: 'Factory', chinese: '工厂' },
      { english: 'General', chinese: '一般' }, { english: 'Habit', chinese: '习惯' }, { english: 'Identify', chinese: '鉴定' },
      { english: 'Journey', chinese: '旅程' }, { english: 'Knowledge', chinese: '知识' }, { english: 'Language', chinese: '语言' },
      { english: 'Machine', chinese: '机器' }, { english: 'Natural', chinese: '自然' }, { english: 'Object', chinese: '物体' },
      { english: 'Patient', chinese: '耐心' }, { english: 'Quality', chinese: '质量' }, { english: 'Rapid', chinese: '迅速' },
      { english: 'Safety', chinese: '安全' }, { english: 'Target', chinese: '目标' }, { english: 'Unable', chinese: '不能' },
      { english: 'Value', chinese: '价值' }, { english: 'Wealth', chinese: '财富' }, { english: 'Yesterday', chinese: '昨天' },
      { english: 'Zoo', chinese: '动物园' }, { english: 'Balance', chinese: '平衡' }, { english: 'Camera', chinese: '照相机' },
      { english: 'Daily', chinese: '日常的' }, { english: 'Eager', chinese: '渴望的' }, { english: 'Famous', chinese: '著名的' },
      { english: 'Gather', chinese: '聚集' }, { english: 'Happen', chinese: '发生' }, { english: 'Image', chinese: '图像' },
      { english: 'Jacket', chinese: '夹克' }, { english: 'Keep', chinese: '保持' }, { english: 'Labor', chinese: '劳动' },
      { english: 'Manage', chinese: '管理' }, { english: 'Nation', chinese: '国家' }, { english: 'Obey', chinese: '服从' },
      { english: 'Pain', chinese: '疼痛' }, { english: 'Quick', chinese: '快的' }, { english: 'Race', chinese: '比赛' },
      { english: 'Satisfy', chinese: '满足' }, { english: 'Task', chinese: '任务' }, { english: 'Ugly', chinese: '丑陋的' },
      { english: 'Vacation', chinese: '假期' }, { english: 'Wake', chinese: '醒来' }, { english: 'Yard', chinese: '院子' },
      { english: 'Zeal', chinese: '热情' }, { english: 'Abroad', chinese: '在国外' }, { english: 'Baby', chinese: '婴儿' },
      { english: 'Cake', chinese: '蛋糕' }, { english: 'Dance', chinese: '跳舞' }, { english: 'Early', chinese: '早的' },
      { english: 'Face', chinese: '脸' }, { english: 'Game', chinese: '游戏' }, { english: 'Hair', chinese: '头发' },
      { english: 'Ice', chinese: '冰' }, { english: 'Job', chinese: '工作' }, { english: 'Key', chinese: '钥匙' },
      { english: 'Late', chinese: '晚的' }, { english: 'Mail', chinese: '邮件' }, { english: 'Name', chinese: '名字' },
      { english: 'Office', chinese: '办公室' }, { english: 'Paper', chinese: '纸' }, { english: 'Queen', chinese: '女王' },
      { english: 'Radio', chinese: '收音机' }, { english: 'Sad', chinese: '悲伤的' }, { english: 'Table', chinese: '桌子' },
      { english: 'Uncle', chinese: '叔叔' }, { english: 'Valley', chinese: '山谷' }, { english: 'Wait', chinese: '等待' },
      { english: 'Year', chinese: '年' }, { english: 'Zone', chinese: '地带' }, { english: 'Above', chinese: '在上面' },
      { english: 'Bank', chinese: '银行' }, { english: 'Camp', chinese: '营地' }, { english: 'Dark', chinese: '黑暗的' },
      { english: 'East', chinese: '东方' }, { english: 'Fair', chinese: '公平的' }, { english: 'Garden', chinese: '花园' },
      { english: 'Half', chinese: '一半' }, { english: 'Idea', chinese: '主意' }, { english: 'Joke', chinese: '玩笑' },
      { english: 'King', chinese: '国王' }, { english: 'Lady', chinese: '女士' }, { english: 'Mad', chinese: '疯狂的' },
      { english: 'Near', chinese: '近的' }, { english: 'Ocean', chinese: '海洋' }, { english: 'Page', chinese: '页' },
      { english: 'Quiet', chinese: '安静的' }, { english: 'Rain', chinese: '雨' }, { english: 'Salt', chinese: '盐' },
      { english: 'Tall', chinese: '高的' }, { english: 'Unit', chinese: '单元' }, { english: 'Vast', chinese: '巨大的' },
      { english: 'Walk', chinese: '步行' }, { english: 'Zero', chinese: '零' }, { english: 'Accept', chinese: '接受' },
      { english: 'Base', chinese: '基础' }, { english: 'Card', chinese: '卡片' }, { english: 'Date', chinese: '日期' },
      { english: 'Easy', chinese: '容易的' }, { english: 'Fall', chinese: '落下' }, { english: 'Gate', chinese: '大门' },
      { english: 'Hall', chinese: '大厅' }, { english: 'Ill', chinese: '生病的' }, { english: 'Join', chinese: '加入' },
      { english: 'Kick', chinese: '踢' }, { english: 'Lake', chinese: '湖' }, { english: 'Make', chinese: '制造' },
      { english: 'Need', chinese: '需要' }, { english: 'Oil', chinese: '油' }, { english: 'Part', chinese: '部分' },
      { english: 'Quarter', chinese: '四分之一' }, { english: 'Rate', chinese: '比率' }, { english: 'Same', chinese: '相同的' },
      { english: 'Talk', chinese: '谈话' }, { english: 'Use', chinese: '使用' }, { english: 'View', chinese: '风景' },
      { english: 'Wash', chinese: '洗' }, { english: 'Active', chinese: '活跃的' }, { english: 'Bear', chinese: '熊' },
      { english: 'Care', chinese: '关心' }, { english: 'Dear', chinese: '亲爱的' }, { english: 'Eat', chinese: '吃' },
      { english: 'Farm', chinese: '农场' }, { english: 'Gift', chinese: '礼物' }, { english: 'Hand', chinese: '手' },
      { english: 'Ink', chinese: '墨水' }, { english: 'Joy', chinese: '欢乐' }, { english: 'Kind', chinese: '种' },
      { english: 'Land', chinese: '陆地' }, { english: 'Many', chinese: '许多' }, { english: 'New', chinese: '新的' },
      { english: 'Old', chinese: '老的' }, { english: 'Pass', chinese: '通过' }, { english: 'Real', chinese: '真实的' },
      { english: 'Save', chinese: '保存' }, { english: 'Team', chinese: '队' }, { english: 'Visit', chinese: '参观' },
      { english: 'Wave', chinese: '波浪' }, { english: 'Act', chinese: '行动' }, { english: 'Beat', chinese: '击败' },
      { english: 'Case', chinese: '情况' }, { english: 'Deep', chinese: '深的' }, { english: 'Edge', chinese: '边缘' },
      { english: 'Fast', chinese: '快的' }, { english: 'Girl', chinese: '女孩' }, { english: 'Hard', chinese: '困难的' },
      { english: 'Iron', chinese: '铁' }, { english: 'Just', chinese: '刚才' }, { english: 'Kill', chinese: '杀死' },
      { english: 'Law', chinese: '法律' }, { english: 'Mark', chinese: '记号' }, { english: 'Next', chinese: '下一个' },
      { english: 'Open', chinese: '打开' }, { english: 'Past', chinese: '过去' }, { english: 'Red', chinese: '红色' },
      { english: 'Sea', chinese: '海' }, { english: 'Tell', chinese: '告诉' }, { english: 'Very', chinese: '非常' },
      { english: 'Wear', chinese: '穿' }, { english: 'Add', chinese: '增加' }, { english: 'Bed', chinese: '床' },
      { english: 'Cast', chinese: '投掷' }, { english: 'Desk', chinese: '书桌' }, { english: 'Egg', chinese: '鸡蛋' },
      { english: 'Fear', chinese: '害怕' }, { english: 'Glad', chinese: '高兴的' }, { english: 'Head', chinese: '头' },
      { english: 'Ice', chinese: '冰' }, { english: 'Jump', chinese: '跳' }, { english: 'Kiss', chinese: '吻' },
      { english: 'Left', chinese: '左边' }, { english: 'Mass', chinese: '大量' }, { english: 'Nice', chinese: '美好的' },
      { english: 'Order', chinese: '命令' }, { english: 'Pay', chinese: '支付' }, { english: 'Rest', chinese: '休息' },
      { english: 'Seat', chinese: '座位' }, { english: 'Term', chinese: '学期' }, { english: 'Voice', chinese: '声音' },
      { english: 'Week', chinese: '周' }
    ]
  },
  {
    id: 'cet4',
    name: '四级 (CET-4)',
    words: [
      { english: 'Abandon', chinese: '放弃' }, { english: 'Benefit', chinese: '利益' }, { english: 'Candidate', chinese: '候选人' },
      { english: 'Debate', chinese: '辩论' }, { english: 'Efficient', chinese: '高效' }, { english: 'Factor', chinese: '因素' },
      { english: 'Generate', chinese: '产生' }, { english: 'Habitat', chinese: '栖息地' }, { english: 'Illegal', chinese: '非法的' },
      { english: 'Jealous', chinese: '嫉妒的' }, { english: 'Launch', chinese: '发射' }, { english: 'Maintain', chinese: '维持' },
      { english: 'Negative', chinese: '消极的' }, { english: 'Obstacle', chinese: '障碍' }, { english: 'Panel', chinese: '面板' },
      { english: 'Racial', chinese: '种族的' }, { english: 'Scale', chinese: '规模' }, { english: 'Tedious', chinese: '乏味的' },
      { english: 'Ultimate', chinese: '最终的' }, { english: 'Vacant', chinese: '空缺的' }, { english: 'Welfare', chinese: '福利' },
      { english: 'Yield', chinese: '产量' }, { english: 'Zone', chinese: '区域' }, { english: 'Absorb', chinese: '吸收' },
      { english: 'Barrier', chinese: '障碍' }, { english: 'Career', chinese: '事业' }, { english: 'Decade', chinese: '十年' },
      { english: 'Editor', chinese: '编辑' }, { english: 'Fabric', chinese: '织物' }, { english: 'Gallery', chinese: '画廊' },
      { english: 'Halt', chinese: '停止' }, { english: 'Ideal', chinese: '理想的' }, { english: 'Jar', chinese: '罐子' },
      { english: 'Keen', chinese: '敏锐的' }, { english: 'Label', chinese: '标签' }, { english: 'Magnet', chinese: '磁铁' },
      { english: 'Naked', chinese: '裸露的' }, { english: 'Obey', chinese: '服从' }, { english: 'Pace', chinese: '步伐' },
      { english: 'Quote', chinese: '引用' }, { english: 'Radar', chinese: '雷达' }, { english: 'Sack', chinese: '麻袋' },
      { english: 'Tailor', chinese: '裁缝' }, { english: 'Undergo', chinese: '经历' }, { english: 'Vague', chinese: '模糊的' },
      { english: 'Wage', chinese: '工资' }, { english: 'Yard', chinese: '院子' }, { english: 'Zeal', chinese: '热情' },
      { english: 'Access', chinese: '入口' }, { english: 'Ban', chinese: '禁止' }, { english: 'Cargo', chinese: '货物' },
      { english: 'Deck', chinese: '甲板' }, { english: 'Earn', chinese: '赚得' }, { english: 'Fade', chinese: '褪色' },
      { english: 'Gap', chinese: '缺口' }, { english: 'Handy', chinese: '手边的' }, { english: 'Idle', chinese: '空闲的' },
      { english: 'Jaw', chinese: '下巴' }, { english: 'Keep', chinese: '保持' }, { english: 'Lack', chinese: '缺乏' },
      { english: 'Maid', chinese: '女仆' }, { english: 'Nap', chinese: '小睡' }, { english: 'Oath', chinese: '誓言' },
      { english: 'Pack', chinese: '包' }, { english: 'Quit', chinese: '离开' }, { english: 'Rag', chinese: '破布' },
      { english: 'Sail', chinese: '航行' }, { english: 'Tank', chinese: '坦克' }, { english: 'Undo', chinese: '取消' },
      { english: 'Vain', chinese: '徒劳的' }, { english: 'Wait', chinese: '等待' }, { english: 'Abuse', chinese: '滥用' },
      { english: 'Bake', chinese: '烘烤' }, { english: 'Cast', chinese: '投掷' }, { english: 'Data', chinese: '数据' },
      { english: 'Ease', chinese: '安逸' }, { english: 'Fail', chinese: '失败' }, { english: 'Gain', chinese: '获得' },
      { english: 'Harm', chinese: '伤害' }, { english: 'Icon', chinese: '图标' }, { english: 'Jazz', chinese: '爵士乐' },
      { english: 'Kid', chinese: '小孩' }, { english: 'Lag', chinese: '落后' }, { english: 'Mail', chinese: '邮件' },
      { english: 'Navy', chinese: '海军' }, { english: 'Odd', chinese: '奇怪的' }, { english: 'Pain', chinese: '疼痛' },
      { english: 'Quiz', chinese: '测验' }, { english: 'Rail', chinese: '铁路' }, { english: 'Safe', chinese: '安全的' },
      { english: 'Tape', chinese: '磁带' }, { english: 'Unit', chinese: '单位' }, { english: 'Vast', chinese: '广阔的' },
      { english: 'Wake', chinese: '醒来' }, { english: 'Acid', chinese: '酸' }, { english: 'Bald', chinese: '秃头的' },
      { english: 'Cave', chinese: '洞穴' }, { english: 'Dawn', chinese: '黎明' }, { english: 'Echo', chinese: '回声' },
      { english: 'Fair', chinese: '公平的' }, { english: 'Gate', chinese: '大门' }, { english: 'Hawk', chinese: '鹰' },
      { english: 'Idol', chinese: '偶像' }, { english: 'Jeep', chinese: '吉普车' }, { english: 'Kill', chinese: '杀死' },
      { english: 'Lane', chinese: '车道' }, { english: 'Male', chinese: '男性' }, { english: 'Near', chinese: '近的' },
      { english: 'Omit', chinese: '省略' }, { english: 'Pale', chinese: '苍白的' }, { english: 'Quilt', chinese: '被子' },
      { english: 'Rain', chinese: '雨' }, { english: 'Salt', chinese: '盐' }, { english: 'Tax', chinese: '税' },
      { english: 'Urge', chinese: '催促' }, { english: 'Veil', chinese: '面纱' }, { english: 'Walk', chinese: '步行' },
      { english: 'Acre', chinese: '英亩' }, { english: 'Band', chinese: '乐队' }, { english: 'Cell', chinese: '细胞' },
      { english: 'Deaf', chinese: '聋的' }, { english: 'Edit', chinese: '编辑' }, { english: 'Fame', chinese: '名声' },
      { english: 'Gaze', chinese: '凝视' }, { english: 'Heal', chinese: '治愈' }, { english: 'Iron', chinese: '铁' },
      { english: 'Jet', chinese: '喷气式飞机' }, { english: 'Knee', chinese: '膝盖' }, { english: 'Last', chinese: '最后的' },
      { english: 'Mass', chinese: '大量' }, { english: 'Neat', chinese: '整洁的' }, { english: 'Oral', chinese: '口头的' },
      { english: 'Palm', chinese: '手掌' }, { english: 'Rare', chinese: '稀有的' }, { english: 'Sand', chinese: '沙子' },
      { english: 'Tent', chinese: '帐篷' }, { english: 'User', chinese: '用户' }, { english: 'View', chinese: '风景' },
      { english: 'Wall', chinese: '墙' }, { english: 'Aim', chinese: '目标' }, { english: 'Bare', chinese: '赤裸的' },
      { english: 'Chef', chinese: '厨师' }, { english: 'Deal', chinese: '交易' }, { english: 'Edge', chinese: '边缘' },
      { english: 'Fan', chinese: '风扇' }, { english: 'Gear', chinese: '齿轮' }, { english: 'Heat', chinese: '热' },
      { english: 'Item', chinese: '项目' }, { english: 'Job', chinese: '工作' }, { english: 'Knit', chinese: '编织' },
      { english: 'Late', chinese: '迟的' }, { english: 'Mate', chinese: '伙伴' }, { english: 'Nest', chinese: '巢' },
      { english: 'Oven', chinese: '烤箱' }, { english: 'Pan', chinese: '平底锅' }, { english: 'Race', chinese: '比赛' },
      { english: 'Seat', chinese: '座位' }, { english: 'Team', chinese: '队' }, { english: 'Vary', chinese: '变化' },
      { english: 'Warm', chinese: '温暖的' }, { english: 'Ally', chinese: '盟友' }, { english: 'Bark', chinese: '树皮' },
      { english: 'Chip', chinese: '芯片' }, { english: 'Debt', chinese: '债务' }, { english: 'Exit', chinese: '出口' },
      { english: 'Fare', chinese: '票价' }, { english: 'Gene', chinese: '基因' }, { english: 'Hell', chinese: '地狱' },
      { english: 'Inch', chinese: '英寸' }, { english: 'Joy', chinese: '欢乐' }, { english: 'Knot', chinese: '结' },
      { english: 'Lead', chinese: '领导' }, { english: 'Mean', chinese: '意味着' }, { english: 'Next', chinese: '下一个' },
      { english: 'Over', chinese: '结束' }, { english: 'Peak', chinese: '山峰' }, { english: 'Rail', chinese: '栏杆' },
      { english: 'Seed', chinese: '种子' }, { english: 'Term', chinese: '术语' }, { english: 'Vote', chinese: '投票' },
      { english: 'Wash', chinese: '洗' }, { english: 'Also', chinese: '也' }, { english: 'Barn', chinese: '谷仓' },
      { english: 'Cite', chinese: '引用' }, { english: 'Defy', chinese: '违抗' }, { english: 'Envy', chinese: '羡慕' },
      { english: 'Farm', chinese: '农场' }, { english: 'Gift', chinese: '礼物' }, { english: 'Hero', chinese: '英雄' },
      { english: 'Info', chinese: '信息' }, { english: 'Jump', chinese: '跳' }, { english: 'Know', chinese: '知道' },
      { english: 'Lean', chinese: '倾斜' }, { english: 'Meet', chinese: '遇见' }, { english: 'Nice', chinese: '美好的' },
      { english: 'Once', chinese: '一次' }, { english: 'Peer', chinese: '同龄人' }, { english: 'Rank', chinese: '等级' },
      { english: 'Seek', chinese: '寻求' }, { english: 'Test', chinese: '测试' }, { english: 'Veto', chinese: '否决' },
      { english: 'Weak', chinese: '虚弱的' }
    ]
  },
   {
    id: 'cet6',
    name: '六级 (CET-6)',
    words: [
      { english: 'Abnormal', chinese: '反常' }, { english: 'Barren', chinese: '贫瘠' }, { english: 'Comply', chinese: '顺从' },
      { english: 'Diffuse', chinese: '扩散' }, { english: 'Endow', chinese: '捐赠' }, { english: 'Flap', chinese: '拍打' },
      { english: 'Gloom', chinese: '忧郁' }, { english: 'Hinder', chinese: '阻碍' }, { english: 'Impair', chinese: '损害' },
      { english: 'Junction', chinese: '连接' }, { english: 'Knob', chinese: '旋钮' }, { english: 'Latent', chinese: '潜在的' },
      { english: 'Manifest', chinese: '显现' }, { english: 'Nasty', chinese: '肮脏的' }, { english: 'Opaque', chinese: '不透明的' },
      { english: 'Paradox', chinese: '悖论' }, { english: 'Quota', chinese: '配额' }, { english: 'Recede', chinese: '后退' },
      { english: 'Scorn', chinese: '轻蔑' }, { english: 'Tangible', chinese: '有形的' }, { english: 'Unanimous', chinese: '一致的' },
      { english: 'Vent', chinese: '发泄' }, { english: 'Wrench', chinese: '猛扭' }, { english: 'Yearn', chinese: '渴望' },
      { english: 'Zenith', chinese: '顶峰' }, { english: 'Adjacent', chinese: '邻近的' }, { english: 'Bizarre', chinese: '奇异的' },
      { english: 'Corrode', chinese: '腐蚀' }, { english: 'Dismay', chinese: '沮丧' }, { english: 'Expire', chinese: '期满' },
      { english: 'Fraud', chinese: '欺诈' }, { english: 'Groan', chinese: '呻吟' }, { english: 'Hoover', chinese: '吸尘器' },
      { english: 'Incentive', chinese: '激励' }, { english: 'Jeopardize', chinese: '危及' }, { english: 'Kinetic', chinese: '动力的' },
      { english: 'Legacy', chinese: '遗产' }, { english: 'Mediate', chinese: '调解' }, { english: 'Nominal', chinese: '名义上的' },
      { english: 'Optimum', chinese: '最佳的' }, { english: 'Pasture', chinese: '牧场' }, { english: 'Quest', chinese: '探索' },
      { english: 'Reclaim', chinese: '收回' }, { english: 'Shove', chinese: '推' }, { english: 'Temperament', chinese: '气质' },
      { english: 'Underlie', chinese: '构成...基础' }, { english: 'Versatile', chinese: '多才多艺的' }, { english: 'Wary', chinese: '谨慎的' },
      { english: 'Yacht', chinese: '游艇' }, { english: 'Zealous', chinese: '热心的' }, { english: 'Affiliate', chinese: '使附属' },
      { english: 'Bleak', chinese: '荒凉的' }, { english: 'Criterion', chinese: '标准' }, { english: 'Divert', chinese: '转移' },
      { english: 'Exquisite', chinese: '精致的' }, { english: 'Fringe', chinese: '边缘' }, { english: 'Grieve', chinese: '悲伤' },
      { english: 'Hypocrisy', chinese: '伪善' }, { english: 'Induce', chinese: '诱导' }, { english: 'Jolt', chinese: '颠簸' },
      { english: 'Kit', chinese: '工具箱' }, { english: 'Linger', chinese: '逗留' }, { english: 'Mingle', chinese: '混合' },
      { english: 'Notify', chinese: '通知' }, { english: 'Outfit', chinese: '装备' }, { english: 'Plausible', chinese: '貌似合理的' },
      { english: 'Quiver', chinese: '颤抖' }, { english: 'Refute', chinese: '反驳' }, { english: 'Slack', chinese: '松弛的' },
      { english: 'Tentative', chinese: '试验性的' }, { english: 'Uphold', chinese: '支持' }, { english: 'Vicious', chinese: '恶毒的' },
      { english: 'Weary', chinese: '疲倦的' }, { english: 'Allegation', chinese: '指控' }, { english: 'Blunt', chinese: '钝的' },
      { english: 'Cynical', chinese: '愤世嫉俗的' }, { english: 'Doom', chinese: '厄运' }, { english: 'Extinct', chinese: '灭绝的' },
      { english: 'Fuse', chinese: '保险丝' }, { english: 'Grim', chinese: '严酷的' }, { english: 'Hysterics', chinese: '歇斯底里' },
      { english: 'Infer', chinese: '推断' }, { english: 'Judicial', chinese: '司法的' }, { english: 'Keen', chinese: '渴望的' },
      { english: 'Loom', chinese: '隐现' }, { english: 'Mob', chinese: '暴民' }, { english: 'Nurture', chinese: '养育' },
      { english: 'Overt', chinese: '公开的' }, { english: 'Poke', chinese: '戳' }, { english: 'Quota', chinese: '定额' },
      { english: 'Reign', chinese: '统治' }, { english: 'Soar', chinese: '高飞' }, { english: 'Testify', chinese: '作证' },
      { english: 'Uproar', chinese: '骚动' }, { english: 'Void', chinese: '无效的' }, { english: 'Whirl', chinese: '旋转' },
      { english: 'Ambiguous', chinese: '模棱两可的' }, { english: 'Boost', chinese: '促进' }, { english: 'Dazzle', chinese: '使目眩' },
      { english: 'Elapse', chinese: '消逝' }, { english: 'Feast', chinese: '盛宴' }, { english: 'Guilt', chinese: '内疚' },
      { english: 'Hamper', chinese: '妨碍' }, { english: 'Intact', chinese: '完好无损的' }, { english: 'Jury', chinese: '陪审团' },
      { english: 'Knack', chinese: '诀窍' }, { english: 'Lure', chinese: '引诱' }, { english: 'Moan', chinese: '呻吟' },
      { english: 'Numb', chinese: '麻木的' }, { english: 'Oval', chinese: '椭圆形的' }, { english: 'Plea', chinese: '恳求' },
      { english: 'Quote', chinese: '报价' }, { english: 'Rip', chinese: '撕裂' }, { english: 'Span', chinese: '跨度' },
      { english: 'Thrive', chinese: '兴旺' }, { english: 'Urban', chinese: '城市的' }, { english: 'Vulgar', chinese: '粗俗的' },
      { english: 'Wreck', chinese: '失事' }, { english: 'Ample', chinese: '充足的' }, { english: 'Brisk', chinese: '轻快的' },
      { english: 'Deem', chinese: '认为' }, { english: 'Elite', chinese: '精英' }, { english: 'Fake', chinese: '假的' },
      { english: 'Gasp', chinese: '喘气' }, { english: 'Haul', chinese: '拖' }, { english: 'Invoke', chinese: '调用' },
      { english: 'Justify', chinese: '证明...正当' }, { english: 'Knot', chinese: '结' }, { english: 'Lump', chinese: '块' },
      { english: 'Mock', chinese: '嘲笑' }, { english: 'Null', chinese: '无效的' }, { english: 'Oath', chinese: '誓言' },
      { english: 'Plot', chinese: '情节' }, { english: 'Raid', chinese: '突袭' }, { english: 'Spur', chinese: '刺激' },
      { english: 'Tilt', chinese: '倾斜' }, { english: 'Utmost', chinese: '极度的' }, { english: 'Verdict', chinese: '裁决' },
      { english: 'Wrap', chinese: '包裹' }, { english: 'Analogy', chinese: '类比' }, { english: 'Bulk', chinese: '体积' },
      { english: 'Defect', chinese: '缺陷' }, { english: 'Embark', chinese: '从事' }, { english: 'Ferry', chinese: '渡轮' },
      { english: 'Gauge', chinese: '测量' }, { english: 'Heave', chinese: '举起' }, { english: 'Inert', chinese: '惰性的' },
      { english: 'Jam', chinese: '果酱' }, { english: 'Key', chinese: '关键' }, { english: 'Lawn', chinese: '草坪' },
      { english: 'Mode', chinese: '模式' }, { english: 'Nut', chinese: '坚果' }, { english: 'Odd', chinese: '奇怪的' },
      { english: 'Plug', chinese: '插头' }, { english: 'Rash', chinese: '鲁莽的' }, { english: 'Stir', chinese: '搅拌' },
      { english: 'Toll', chinese: '通行费' }, { english: 'Utility', chinese: '效用' }, { english: 'Verse', chinese: '诗句' },
      { english: 'Writ', chinese: '令状' }, { english: 'Anonymous', chinese: '匿名的' }, { english: 'Bump', chinese: '碰撞' },
      { english: 'Defer', chinese: '推迟' }, { english: 'Emit', chinese: '发射' }, { english: 'Feat', chinese: '功绩' },
      { english: 'Gear', chinese: '齿轮' }, { english: 'Hike', chinese: '徒步旅行' }, { english: 'Inject', chinese: '注射' },
      { english: 'Jaw', chinese: '颌' }, { english: 'Kid', chinese: '欺骗' }, { english: 'Leak', chinese: '泄漏' },
      { english: 'Mold', chinese: '模具' }, { english: 'Net', chinese: '净的' }, { english: 'Odor', chinese: '气味' },
      { english: 'Pole', chinese: '杆' }, { english: 'Realm', chinese: '领域' }, { english: 'Strap', chinese: '带子' },
      { english: 'Toss', chinese: '投掷' }, { english: 'Utter', chinese: '完全的' }, { english: 'Vessel', chinese: '血管' },
      { english: 'Wit', chinese: '智慧' }
    ]
  }
];